# Generated by Django 3.2.4 on 2022-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.IntegerField(default=7000),
            preserve_default=False,
        ),
    ]
