# Generated by Django 3.2.4 on 2022-03-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='is_diet',
            field=models.BooleanField(default=False),
        ),
    ]
